import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Download, Printer, Trash2 } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { useAuth } from "@/lib/AuthContext";
import StripPreview from "@/components/booth/StripPreview";
import PolkaDots from "@/components/PolkaDots";
import FaceDoodles from "@/components/FaceDoodles";

const dotted = (v) => { const d = new Date(v); return `${d.getMonth() + 1}.${d.getDate()}.${d.getFullYear()}`; };
export default function MyBooths() { const {user}=useAuth(); const [strips,setStrips]=useState([]); const plan=user?.plan||"free"; const load=async()=>{if(user)setStrips(await base44.entities.Strip.filter({user_id:user.id,saved:true},"-created_at"));}; useEffect(()=>{load(); const off=base44.entities.Strip.subscribe(load);return off;},[user?.id]); const remove=async id=>{setStrips(prev=>prev.filter(s=>s.id!==id));try{await base44.entities.Strip.delete(id);}catch(e){}load();}; const download=strip=>{const link=document.createElement("a");link.href=strip.photo_urls[0];link.download="vendhees-booth-photo";link.click();}; return <div><header className="mb-6"><h1 className="font-heading text-3xl font-extrabold">Strips</h1><p className="mt-1 text-sm text-[#8B8D93]">{plan==="free"?"Your 10 newest strips live here. New strips replace the oldest.":"Your strips are saved for one year."}</p>{plan==="free"&&<Link to="/profile" className="mt-4 inline-block rounded-full bg-[#fff3bf] px-4 py-2 text-sm font-bold text-[#e67700]">Go Premium for more room</Link>}</header>{strips.length?<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{strips.map(strip=><article key={strip.id} className="rounded-[18px] border border-[#D8D9DC] bg-white p-4"><StripPreview template={{name:"Studio Mono"}} photos={strip.photo_urls} className="max-w-[110px] mx-auto"/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-[#8B8D93]">{dotted(strip.created_at)}</span><div className="flex gap-3"><button onClick={()=>download(strip)} aria-label="Download strip" className="text-[#228be6]"><Download size={17}/></button><Link to="/print-shop" aria-label="Order prints" className="text-[#228be6]"><Printer size={17}/></Link><button onClick={()=>remove(strip.id)} aria-label="Delete strip" className="text-[#DC2626]"><Trash2 size={17}/></button></div></div>{strip.expires_at&&<p className="mt-2 text-xs text-[#8B8D93]">Expires {dotted(strip.expires_at)}</p>}</article>)}</div>:<div className="relative isolate overflow-hidden rounded-[18px] border border-dashed border-[#AEB0B5] bg-[#fff0f6] px-6 py-16 text-center"><PolkaDots /><FaceDoodles variant="empty" /><p className="font-heading text-xl font-bold">Start your first booth</p><p className="mt-1 text-sm text-[#8B8D93]">Your finished strips will collect here.</p><Link to="/booth" className="mt-5 inline-block rounded-full bg-[#f06595] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#e64980]">Start a booth</Link></div>}</div>; }